version: "3.9"

services:
    php:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                PHP_VERSION: 8.2.7-fpm-alpine3.18
                XDEBUG_VERSION: 3.2.1
                COMPOSER_VERSION: 2.5.8
                LINUX_USER_ID: 1000
        environment:
            XDEBUG_CONFIG: client_host=host.docker.internal client_port=19500
            PHP_IDE_CONFIG: serverName=class-metadata
        volumes:
            - ./:/srv/app
